version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate contract"
    cmds:
      - protoc -I=proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative proto/auth/auth.proto